@API_URL = http://localhost:8000

GET http://localhost:8000/vulnerabilities

###

POST {{API_URL}}/vulnerabilities
Content-Type: application/json
# Authorization: 
{
    "username": "user1",
    "password": "password1"
}