# Generated by Django 4.0 on 2022-02-06 22:18

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('censys_api_id', models.CharField(default='', max_length=72, unique=True)),
                ('censys_secret', models.CharField(default='', max_length=64, unique=True)),
                ('shodan_username', models.CharField(default='', max_length=200, unique=True)),
                ('shodan_api_key', models.CharField(default='', max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
