# Generated by Django 3.0.6 on 2020-09-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0006_auto_20200926_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwemodel',
            name='tutorial_example',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
