# Generated by Django 3.0.6 on 2020-09-26 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0008_auto_20200926_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwemodel',
            name='rank',
            field=models.PositiveSmallIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(1)]),
        ),
    ]
