# Generated by Django 3.0.6 on 2020-09-26 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0009_cwemodel_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwemodel',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, default=None, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(1)]),
        ),
    ]
