# Generated by Django 3.1.4 on 2021-01-05 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CWEModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cwe_id', models.CharField(max_length=15, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('likehood', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalImpactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cwe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cwe_technical_model', to='api_vulnerabilities.cwemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CVEModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=17, unique=True)),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
                ('cwe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cwe_model', to='api_vulnerabilities.cwemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CausedByModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=350)),
                ('process', models.TextField(max_length=350)),
                ('description', models.TextField()),
                ('cwe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cwe_caused_by', to='api_vulnerabilities.cwemodel')),
            ],
        ),
    ]
