class FeedsUrls:
    def __init__(self):
        self._factordb = "http://factordb.com/"
        self._guerrillamail = "https://www.guerrillamail.com/"
        self._hybrid_analysis = "https://hybrid-analysis.com/"
        self._hunter = "https://hunter.io/"
        self._haveibeenpwned= "https://haveibeenpwned.com/"
        self._hackertarget= "https://hackertarget.com/#"
        self._securityheaders = "https://securityheaders.com/"
        self._jsonviewer = "http://jsonviewer.stack.hu/"
        self._ridter = "https://github.com/Ridter/get_ip_by_ico/blob/master/get_ip_by_ico.py"
        self._base64_visualisation = "https://www.lucidchart.com/techblog/2017/10/23/base64-encoding-a-visual-explanation/"
        self._diffnow = "https://diffnow.com/compare-clips"
        self._cyber_chef = "https://gchq.github.io/CyberChef/"
        self._nmmapper = "https://www.nmmapper.com"
        self._securityforeveryone = "https://securityforeveryone.com/tools/dns-zone-transfer"
