# Generated by Django 3.1.1 on 2020-09-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_cheat_sheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CWEModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True)),
                ('description', models.TextField()),
                ('attack_example', models.TextField(default=None, null=True)),
                ('cve_example', models.CharField(default=None, max_length=20, null=True)),
                ('tutorial_example', models.CharField(default=None, max_length=200, null=True)),
                ('top_25', models.BooleanField(default=False)),
                ('rank', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25')], default='0', max_length=2, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Knowledge_base',
        ),
    ]
