# Generated by Django 3.0.6 on 2020-05-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_cheat_sheet', '0002_auto_20200530_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_cheat_sheet',
            name='number_cwe',
            field=models.IntegerField(unique=True),
        ),
    ]
