# Generated by Django 3.0.6 on 2020-05-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_cheat_sheet', '0003_auto_20200530_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_cheat_sheet',
            name='definition',
            field=models.CharField(max_length=2000),
        ),
    ]
