# Generated by Django 3.0.6 on 2020-09-25 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_cheat_sheet', '0004_auto_20200531_1425'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Knowledge_base',
            new_name='KnowledgeBase',
        ),
    ]
