# Generated by Django 3.0.6 on 2020-09-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_cheat_sheet', '0005_auto_20200926_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='CWEModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True)),
                ('description', models.TextField()),
                ('top_25', models.BooleanField(default=False)),
                ('attack_example', models.TextField(null=True)),
                ('cve_example', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='KnowledgeBase',
        ),
    ]
