# Generated by Django 3.0.6 on 2020-09-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_cheat_sheet', '0007_cwemodel_tutorial_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwemodel',
            name='attack_example',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cwemodel',
            name='cve_example',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cwemodel',
            name='tutorial_example',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
