# Generated by Django 3.0.6 on 2020-09-25 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_searcher', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
