# Generated by Django 3.1.1 on 2020-12-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_searcher', '0002_auto_20201218_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvemodel',
            name='cve_id',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='cwemodel',
            name='cwe_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
