# Generated by Django 3.1.4 on 2021-01-05 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_searcher', '0004_auto_20201220_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvemodel',
            name='cwe',
        ),
        migrations.RemoveField(
            model_name='technicalimpactmodel',
            name='cwe',
        ),
        migrations.DeleteModel(
            name='CausedByModel',
        ),
        migrations.DeleteModel(
            name='CVEModel',
        ),
        migrations.DeleteModel(
            name='CWEModel',
        ),
        migrations.DeleteModel(
            name='TechnicalImpactModel',
        ),
    ]
