export const cveList = [
  {
    id: 12389,
    cwe_code: "CWE-1004",
    description:
      "In PEPPERL+FUCHS WirelessHART-Gateway 3.0.8 and 3.0.9 the HttpOnly attribute is not set on a cookie. This allows the cookie's value to be read or set by client-side JavaScript.",
    code: "CVE-2021-34563",
    published: "2021-08-31T11:15Z",
    modified: "2021-09-09T14:21Z",
    version: "4.0",
    assigner: "info@cert.vde.com",
    data_format: "MITRE",
    references_list: [
      {
        name: "https://cert.vde.com/en-us/advisories/vde-2021-027",
        url: "https://cert.vde.com/en-us/advisories/vde-2021-027",
        refsource: "CONFIRM",
        tags: ["third_party_advisory"],
      },
    ],
    cpe_list: [],
    base_metric_v2: {
      cvss_v2: {
        vector: "AV:L/AC:L/Au:N/C:P/I:N/A:N",
        version: "2.0",
        access_vector: "LOCAL",
        access_complexity: "LOW",
        authentication: "NONE",
        confidentiality_impact: "PARTIAL",
        integrity_impact: "NONE",
        availability_impact: "NONE",
        base_score: 2.1,
      },
      severity: "LOW",
      exploitability_score: 3.9,
      impact_score: 2.9,
      is_obtain_all_privilege: false,
      is_obtain_user_privilege: false,
      is_obtain_other_privilege: false,
      is_user_interaction_required: false,
    },
    base_metric_v3: {
      cvss_v3: {
        vector: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N",
        version: "3.1",
        attack_vector: "LOCAL",
        attack_complexity: "LOW",
        privileges_required: "LOW",
        user_interaction: "LOW",
        scope: "UNCHANGED",
        confidentiality_impact: "LOW",
        integrity_impact: "NONE",
        availability_impact: "NONE",
        base_score: 3.3,
        base_severity: "LOW",
      },
      exploitability_score: 1.8,
      impact_score: 1.4,
    },
  },

  {
    id: 12390,
    cwe_code: "CWE-315",
    description:
      "Any cookie-stealing vulnerabilities within the application or browser would enable an attacker to steal the user's credentials to the PEPPERL+FUCHS WirelessHART-Gateway 3.0.9.",
    code: "CVE-2021-34564",
    published: "2021-08-31T11:15Z",
    modified: "2021-09-09T14:18Z",
    version: "4.0",
    assigner: "info@cert.vde.com",
    data_format: "MITRE",
    references_list: [
      {
        name: "https://cert.vde.com/en-us/advisories/vde-2021-027",
        url: "https://cert.vde.com/en-us/advisories/vde-2021-027",
        refsource: "CONFIRM",
        tags: ["third_party_advisory"],
      },
    ],
    cpe_list: [],
    base_metric_v2: {
      cvss_v2: {
        vector: "AV:L/AC:L/Au:N/C:P/I:N/A:N",
        version: "2.0",
        access_vector: "LOCAL",
        access_complexity: "LOW",
        authentication: "NONE",
        confidentiality_impact: "PARTIAL",
        integrity_impact: "NONE",
        availability_impact: "NONE",
        base_score: 2.1,
      },
      severity: "LOW",
      exploitability_score: 3.9,
      impact_score: 2.9,
      is_obtain_all_privilege: false,
      is_obtain_user_privilege: false,
      is_obtain_other_privilege: false,
      is_user_interaction_required: false,
    },
    base_metric_v3: {
      cvss_v3: {
        vector: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
        version: "3.1",
        attack_vector: "LOCAL",
        attack_complexity: "LOW",
        privileges_required: "LOW",
        user_interaction: "LOW",
        scope: "UNCHANGED",
        confidentiality_impact: "HIGH",
        integrity_impact: "NONE",
        availability_impact: "NONE",
        base_score: 5.5,
        base_severity: "MEDIUM",
      },
      exploitability_score: 1.8,
      impact_score: 3.6,
    },
  },
  {
    id: 17389,
    cwe_code: "CWE-603",
    description:
      'A vulnerability has been identified in SIPORT MP (All versions < 3.2.1). Vulnerable versions of the device could allow an authenticated attacker to impersonate other users of the system and perform (potentially administrative) actions on behalf of those users if the single sign-on feature ("Allow logon without password") is enabled.',
    code: "CVE-2020-7591",
    published: "2020-10-15T19:15Z",
    modified: "2022-06-15T03:15Z",
    version: "4.0",
    assigner: "productcert@siemens.com",
    data_format: "MITRE",
    references_list: [
      {
        name: "https://cert-portal.siemens.com/productcert/pdf/ssa-384879.pdf",
        url: "https://cert-portal.siemens.com/productcert/pdf/ssa-384879.pdf",
        refsource: "MISC",
        tags: ["vendor_advisory"],
      },
      {
        name: "https://us-cert.cisa.gov/ics/advisories/icsa-20-287-06",
        url: "https://us-cert.cisa.gov/ics/advisories/icsa-20-287-06",
        refsource: "MISC",
        tags: ["third_party_advisory", "us_government_resource"],
      },
    ],
    cpe_list: [
      {
        uri: "cpe:2.3:a:siemens:siport_mp:*:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
    ],
    base_metric_v2: {
      cvss_v2: {
        vector: "AV:N/AC:M/Au:S/C:C/I:C/A:C",
        version: "2.0",
        access_vector: "NETWORK",
        access_complexity: "MEDIUM",
        authentication: "SINGLE",
        confidentiality_impact: "COMPLETE",
        integrity_impact: "COMPLETE",
        availability_impact: "COMPLETE",
        base_score: 8.5,
      },
      severity: "HIGH",
      exploitability_score: 6.8,
      impact_score: 10.0,
      is_obtain_all_privilege: false,
      is_obtain_user_privilege: false,
      is_obtain_other_privilege: false,
      is_user_interaction_required: false,
    },
    base_metric_v3: {
      cvss_v3: {
        vector: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
        version: "3.1",
        attack_vector: "NETWORK",
        attack_complexity: "LOW",
        privileges_required: "LOW",
        user_interaction: "LOW",
        scope: "UNCHANGED",
        confidentiality_impact: "HIGH",
        integrity_impact: "HIGH",
        availability_impact: "HIGH",
        base_score: 8.8,
        base_severity: "HIGH",
      },
      exploitability_score: 2.8,
      impact_score: 5.9,
    },
  },
  {
    id: 2961,
    cwe_code: "CWE-527",
    description:
      '`projen` is a project generation tool that synthesizes project configuration files such as `package.json`, `tsconfig.json`, `.gitignore`, GitHub Workflows, `eslint`, `jest`, and more, from a well-typed definition written in JavaScript. Users of projen\'s `NodeProject` project type (including any project type derived from it) include a `.github/workflows/rebuild-bot.yml` workflow that may allow any GitHub user to trigger execution of un-trusted code in the context of the "main" repository (as opposed to that of a fork). In some situations, such untrusted code may potentially be able to commit to the "main" repository. The rebuild-bot workflow is triggered by comments including `@projen rebuild` on pull-request to trigger a re-build of the projen project, and updating the pull request with the updated files. This workflow is triggered by an `issue_comment` event, and thus always executes with a `GITHUB_TOKEN` belonging to the repository into which the pull-request is made (this is in contrast with workflows triggered by `pull_request` events, which always execute with a `GITHUB_TOKEN` belonging to the repository from which the pull-request is made). Repositories that do not have branch protection configured on their default branch (typically `main` or `master`) could possibly allow an untrusted user to gain access to secrets configured on the repository (such as NPM tokens, etc). Branch protection prohibits this escalation, as the managed `GITHUB_TOKEN` would not be able to modify the contents of a protected branch and affected workflows must be defined on the default branch.',
    code: "CVE-2021-21423",
    published: "2021-04-06T19:15Z",
    modified: "2021-04-15T14:37Z",
    version: "4.0",
    assigner: "security-advisories@github.com",
    data_format: "MITRE",
    references_list: [
      {
        name: "https://github.com/projen/projen/security/advisories/GHSA-gg2g-m5wc-vccq",
        url: "https://github.com/projen/projen/security/advisories/GHSA-gg2g-m5wc-vccq",
        refsource: "CONFIRM",
        tags: ["mitigation", "third_party_advisory"],
      },
      {
        name: "https://github.com/projen/projen/commit/36030c6a4b1acd0054673322612e7c70e9446643",
        url: "https://github.com/projen/projen/commit/36030c6a4b1acd0054673322612e7c70e9446643",
        refsource: "MISC",
        tags: ["patch", "third_party_advisory"],
      },
      {
        name: "https://www.npmjs.com/package/projen",
        url: "https://www.npmjs.com/package/projen",
        refsource: "MISC",
        tags: ["product", "third_party_advisory"],
      },
    ],
    cpe_list: [
      {
        uri: "cpe:2.3:a:projen_project:projen:*:*:*:*:*:node.js:*:*",
        is_vulnerable: true,
      },
    ],
    base_metric_v2: {
      cvss_v2: {
        vector: "AV:N/AC:L/Au:S/C:P/I:P/A:N",
        version: "2.0",
        access_vector: "NETWORK",
        access_complexity: "LOW",
        authentication: "SINGLE",
        confidentiality_impact: "PARTIAL",
        integrity_impact: "PARTIAL",
        availability_impact: "NONE",
        base_score: 5.5,
      },
      severity: "MEDIUM",
      exploitability_score: 8.0,
      impact_score: 4.9,
      is_obtain_all_privilege: false,
      is_obtain_user_privilege: false,
      is_obtain_other_privilege: false,
      is_user_interaction_required: false,
    },
    base_metric_v3: {
      cvss_v3: {
        vector: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
        version: "3.1",
        attack_vector: "NETWORK",
        attack_complexity: "LOW",
        privileges_required: "LOW",
        user_interaction: "LOW",
        scope: "UNCHANGED",
        confidentiality_impact: "HIGH",
        integrity_impact: "HIGH",
        availability_impact: "NONE",
        base_score: 8.1,
        base_severity: "HIGH",
      },
      exploitability_score: 2.8,
      impact_score: 5.2,
    },
  },
  {
    id: 1959,
    cwe_code: "CWE-707",
    description:
      "In nghttp2 before version 1.41.0, the overly large HTTP/2 SETTINGS frame payload causes denial of service. The proof of concept attack involves a malicious client constructing a SETTINGS frame with a length of 14,400 bytes (2400 individual settings entries) over and over again. The attack causes the CPU to spike at 100%. nghttp2 v1.41.0 fixes this vulnerability. There is a workaround to this vulnerability. Implement nghttp2_on_frame_recv_callback callback, and if received frame is SETTINGS frame and the number of settings entries are large (e.g., > 32), then drop the connection.",
    code: "CVE-2020-11080",
    published: "2020-06-03T23:15Z",
    modified: "2022-05-12T15:00Z",
    version: "4.0",
    assigner: "security-advisories@github.com",
    data_format: "MITRE",
    references_list: [
      {
        name: "https://github.com/nghttp2/nghttp2/commit/f8da73bd042f810f34d19f9eae02b46d870af394",
        url: "https://github.com/nghttp2/nghttp2/commit/f8da73bd042f810f34d19f9eae02b46d870af394",
        refsource: "MISC",
        tags: ["patch", "third_party_advisory"],
      },
      {
        name: "https://github.com/nghttp2/nghttp2/security/advisories/GHSA-q5wr-xfw9-q7xr",
        url: "https://github.com/nghttp2/nghttp2/security/advisories/GHSA-q5wr-xfw9-q7xr",
        refsource: "CONFIRM",
        tags: ["patch", "third_party_advisory"],
      },
      {
        name: "https://github.com/nghttp2/nghttp2/commit/336a98feb0d56b9ac54e12736b18785c27f75090",
        url: "https://github.com/nghttp2/nghttp2/commit/336a98feb0d56b9ac54e12736b18785c27f75090",
        refsource: "MISC",
        tags: ["patch", "third_party_advisory"],
      },
      {
        name: "DSA-4696",
        url: "https://www.debian.org/security/2020/dsa-4696",
        refsource: "DEBIAN",
        tags: ["third_party_advisory"],
      },
      {
        name: "openSUSE-SU-2020:0802",
        url: "http://lists.opensuse.org/opensuse-security-announce/2020-06/msg00024.html",
        refsource: "SUSE",
        tags: ["mailing_list", "third_party_advisory"],
      },
      {
        name: "FEDORA-2020-f7d15c8b77",
        url: "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AAC2AA36OTRHKSVM5OV7TTVB3CZIGEFL/",
        refsource: "FEDORA",
        tags: ["third_party_advisory"],
      },
      {
        name: "https://www.oracle.com/security-alerts/cpujul2020.html",
        url: "https://www.oracle.com/security-alerts/cpujul2020.html",
        refsource: "MISC",
        tags: ["third_party_advisory"],
      },
      {
        name: "https://www.oracle.com/security-alerts/cpuoct2020.html",
        url: "https://www.oracle.com/security-alerts/cpuoct2020.html",
        refsource: "MISC",
        tags: ["third_party_advisory"],
      },
      {
        name: "FEDORA-2020-43d5a372fc",
        url: "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4OOYAMJVLLCLXDTHW3V5UXNULZBBK4O6/",
        refsource: "FEDORA",
        tags: ["third_party_advisory"],
      },
      {
        name: "https://www.oracle.com/security-alerts/cpujan2021.html",
        url: "https://www.oracle.com/security-alerts/cpujan2021.html",
        refsource: "MISC",
        tags: ["third_party_advisory"],
      },
      {
        name: "N/A",
        url: "https://www.oracle.com//security-alerts/cpujul2021.html",
        refsource: "N/A",
        tags: ["not_applicable", "third_party_advisory"],
      },
      {
        name: "[debian-lts-announce] 20211017 [SECURITY] [DLA 2786-1] nghttp2 security update",
        url: "https://lists.debian.org/debian-lts-announce/2021/10/msg00011.html",
        refsource: "MLIST",
        tags: ["mailing_list", "third_party_advisory"],
      },
      {
        name: "https://www.oracle.com/security-alerts/cpuapr2022.html",
        url: "https://www.oracle.com/security-alerts/cpuapr2022.html",
        refsource: "MISC",
        tags: ["patch", "third_party_advisory"],
      },
    ],
    cpe_list: [
      {
        uri: "cpe:2.3:a:nghttp2:nghttp2:*:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:o:debian:debian_linux:9.0:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:o:debian:debian_linux:10.0:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:o:opensuse:leap:15.1:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:o:fedoraproject:fedora:31:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:o:fedoraproject:fedora:33:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:a:oracle:enterprise_communications_broker:3.1.0:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:a:oracle:graalvm:19.3.2:*:*:*:enterprise:*:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:a:oracle:graalvm:20.1.0:*:*:*:enterprise:*:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:a:oracle:mysql:*:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:a:oracle:enterprise_communications_broker:3.2.0:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:a:oracle:mysql:*:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:a:oracle:mysql:*:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:a:oracle:mysql:*:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:a:oracle:mysql:*:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:a:oracle:banking_extensibility_workbench:14.3.0:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:a:oracle:banking_extensibility_workbench:14.4.0:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:a:oracle:blockchain_platform:*:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
    ],
    base_metric_v2: {
      cvss_v2: {
        vector: "AV:N/AC:L/Au:N/C:N/I:N/A:P",
        version: "2.0",
        access_vector: "NETWORK",
        access_complexity: "LOW",
        authentication: "NONE",
        confidentiality_impact: "NONE",
        integrity_impact: "NONE",
        availability_impact: "PARTIAL",
        base_score: 5.0,
      },
      severity: "MEDIUM",
      exploitability_score: 10.0,
      impact_score: 2.9,
      is_obtain_all_privilege: false,
      is_obtain_user_privilege: false,
      is_obtain_other_privilege: false,
      is_user_interaction_required: false,
    },
    base_metric_v3: {
      cvss_v3: {
        vector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
        version: "3.1",
        attack_vector: "NETWORK",
        attack_complexity: "LOW",
        privileges_required: "NONE",
        user_interaction: "NONE",
        scope: "UNCHANGED",
        confidentiality_impact: "NONE",
        integrity_impact: "NONE",
        availability_impact: "HIGH",
        base_score: 7.5,
        base_severity: "HIGH",
      },
      exploitability_score: 3.9,
      impact_score: 3.6,
    },
  },
  {
    id: 973,
    cwe_code: "CWE-707",
    description:
      "An issue was discovered in Suricata 4.1.3. If the network packet does not have the right length, the parser tries to access a part of a DHCP packet. At this point, the Rust environment runs into a panic in parse_clientid_option in the dhcp/parser.rs file.",
    code: "CVE-2019-10052",
    published: "2019-08-28T20:15Z",
    modified: "2019-09-04T19:59Z",
    version: "4.0",
    assigner: "cve@mitre.org",
    data_format: "MITRE",
    references_list: [
      {
        name: "https://redmine.openinfosecfoundation.org/issues/2947",
        url: "https://redmine.openinfosecfoundation.org/issues/2947",
        refsource: "MISC",
        tags: ["exploit", "issue_tracking", "third_party_advisory"],
      },
      {
        name: "https://suricata-ids.org/2019/04/30/suricata-4-1-4-released/",
        url: "https://suricata-ids.org/2019/04/30/suricata-4-1-4-released/",
        refsource: "CONFIRM",
        tags: ["release_notes", "vendor_advisory"],
      },
      {
        name: "https://redmine.openinfosecfoundation.org/issues/2902",
        url: "https://redmine.openinfosecfoundation.org/issues/2902",
        refsource: "MISC",
        tags: ["exploit", "issue_tracking", "third_party_advisory"],
      },
    ],
    cpe_list: [
      {
        uri: "cpe:2.3:a:suricata-ids:suricata:4.1.3:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
    ],
    base_metric_v2: {
      cvss_v2: {
        vector: "AV:N/AC:L/Au:N/C:N/I:N/A:P",
        version: "2.0",
        access_vector: "NETWORK",
        access_complexity: "LOW",
        authentication: "NONE",
        confidentiality_impact: "NONE",
        integrity_impact: "NONE",
        availability_impact: "PARTIAL",
        base_score: 5.0,
      },
      severity: "MEDIUM",
      exploitability_score: 10.0,
      impact_score: 2.9,
      is_obtain_all_privilege: false,
      is_obtain_user_privilege: false,
      is_obtain_other_privilege: false,
      is_user_interaction_required: false,
    },
    base_metric_v3: {
      cvss_v3: {
        vector: "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
        version: "3.0",
        attack_vector: "NETWORK",
        attack_complexity: "LOW",
        privileges_required: "NONE",
        user_interaction: "NONE",
        scope: "UNCHANGED",
        confidentiality_impact: "NONE",
        integrity_impact: "NONE",
        availability_impact: "HIGH",
        base_score: 7.5,
        base_severity: "HIGH",
      },
      exploitability_score: 3.9,
      impact_score: 3.6,
    },
  },
  {
    id: 12441,
    cwe_code: "CWE-707",
    description:
      "An exploitable vulnerability exists in the remote servers of Samsung SmartThings Hub STH-ETH-250 - Firmware version 0.20.17. The hubCore process listens on port 39500 and relays any unauthenticated messages to SmartThings' remote servers, which incorrectly handle camera IDs for the 'sync' operation, leading to arbitrary deletion of cameras. An attacker can send an HTTP request to trigger this vulnerability.",
    code: "CVE-2018-3918",
    published: "2018-08-27T15:29Z",
    modified: "2022-04-19T18:15Z",
    version: "4.0",
    assigner: "talos-cna@cisco.com",
    data_format: "MITRE",
    references_list: [
      {
        name: "https://talosintelligence.com/vulnerability_reports/TALOS-2018-0582",
        url: "https://talosintelligence.com/vulnerability_reports/TALOS-2018-0582",
        refsource: "MISC",
        tags: ["exploit", "third_party_advisory"],
      },
    ],
    cpe_list: [],
    base_metric_v2: {
      cvss_v2: {
        vector: "AV:N/AC:L/Au:N/C:N/I:P/A:P",
        version: "2.0",
        access_vector: "NETWORK",
        access_complexity: "LOW",
        authentication: "NONE",
        confidentiality_impact: "NONE",
        integrity_impact: "PARTIAL",
        availability_impact: "PARTIAL",
        base_score: 6.4,
      },
      severity: "MEDIUM",
      exploitability_score: 10.0,
      impact_score: 4.9,
      is_obtain_all_privilege: false,
      is_obtain_user_privilege: false,
      is_obtain_other_privilege: false,
      is_user_interaction_required: false,
    },
    base_metric_v3: {
      cvss_v3: {
        vector: "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
        version: "3.0",
        attack_vector: "NETWORK",
        attack_complexity: "LOW",
        privileges_required: "NONE",
        user_interaction: "NONE",
        scope: "UNCHANGED",
        confidentiality_impact: "NONE",
        integrity_impact: "HIGH",
        availability_impact: "NONE",
        base_score: 7.5,
        base_severity: "HIGH",
      },
      exploitability_score: 3.9,
      impact_score: 3.6,
    },
  },
  {
    id: 14112,
    cwe_code: "CWE-471",
    description:
      "A vulnerability has been identified in SINEMA Remote Connect Server (All versions < V3.0 SP2). The status provided by the syslog clients managed by the affected software can be manipulated by an unauthenticated attacker in the same network of the affected system.",
    code: "CVE-2021-37177",
    published: "2021-09-14T11:15Z",
    modified: "2021-09-23T19:06Z",
    version: "4.0",
    assigner: "productcert@siemens.com",
    data_format: "MITRE",
    references_list: [
      {
        name: "https://cert-portal.siemens.com/productcert/pdf/ssa-334944.pdf",
        url: "https://cert-portal.siemens.com/productcert/pdf/ssa-334944.pdf",
        refsource: "MISC",
        tags: ["patch", "vendor_advisory"],
      },
    ],
    cpe_list: [
      {
        uri: "cpe:2.3:a:siemens:sinema_remote_connect_server:*:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:a:siemens:sinema_remote_connect_server:3.0:sp1:*:*:*:*:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:a:siemens:sinema_remote_connect_server:3.0:-:*:*:*:*:*:*",
        is_vulnerable: true,
      },
    ],
    base_metric_v2: {
      cvss_v2: {
        vector: "AV:A/AC:L/Au:N/C:N/I:P/A:N",
        version: "2.0",
        access_vector: "ADJACENT_NETWORK",
        access_complexity: "LOW",
        authentication: "NONE",
        confidentiality_impact: "NONE",
        integrity_impact: "PARTIAL",
        availability_impact: "NONE",
        base_score: 3.3,
      },
      severity: "LOW",
      exploitability_score: 6.5,
      impact_score: 2.9,
      is_obtain_all_privilege: false,
      is_obtain_user_privilege: false,
      is_obtain_other_privilege: false,
      is_user_interaction_required: false,
    },
    base_metric_v3: {
      cvss_v3: {
        vector: "CVSS:3.1/AV:A/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
        version: "3.1",
        attack_vector: "ADJACENT_NETWORK",
        attack_complexity: "LOW",
        privileges_required: "NONE",
        user_interaction: "NONE",
        scope: "UNCHANGED",
        confidentiality_impact: "NONE",
        integrity_impact: "HIGH",
        availability_impact: "NONE",
        base_score: 6.5,
        base_severity: "MEDIUM",
      },
      exploitability_score: 2.8,
      impact_score: 3.6,
    },
  },
  {
    id: 14130,
    cwe_code: "CWE-471",
    description:
      "A vulnerability has been identified in SINEMA Remote Connect Server (All versions < V3.0 SP2). An unauthenticated attacker in the same network of the affected system could manipulate certain parameters and set a valid user of the affected software as invalid (or vice-versa).",
    code: "CVE-2021-37193",
    published: "2021-09-14T11:15Z",
    modified: "2021-09-23T19:13Z",
    version: "4.0",
    assigner: "productcert@siemens.com",
    data_format: "MITRE",
    references_list: [
      {
        name: "https://cert-portal.siemens.com/productcert/pdf/ssa-334944.pdf",
        url: "https://cert-portal.siemens.com/productcert/pdf/ssa-334944.pdf",
        refsource: "MISC",
        tags: ["patch", "vendor_advisory"],
      },
    ],
    cpe_list: [
      {
        uri: "cpe:2.3:a:siemens:sinema_remote_connect_server:*:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:a:siemens:sinema_remote_connect_server:3.0:sp1:*:*:*:*:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:a:siemens:sinema_remote_connect_server:3.0:-:*:*:*:*:*:*",
        is_vulnerable: true,
      },
    ],
    base_metric_v2: {
      cvss_v2: {
        vector: "AV:A/AC:L/Au:N/C:N/I:P/A:N",
        version: "2.0",
        access_vector: "ADJACENT_NETWORK",
        access_complexity: "LOW",
        authentication: "NONE",
        confidentiality_impact: "NONE",
        integrity_impact: "PARTIAL",
        availability_impact: "NONE",
        base_score: 3.3,
      },
      severity: "LOW",
      exploitability_score: 6.5,
      impact_score: 2.9,
      is_obtain_all_privilege: false,
      is_obtain_user_privilege: false,
      is_obtain_other_privilege: false,
      is_user_interaction_required: false,
    },
    base_metric_v3: {
      cvss_v3: {
        vector: "CVSS:3.1/AV:A/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
        version: "3.1",
        attack_vector: "ADJACENT_NETWORK",
        attack_complexity: "LOW",
        privileges_required: "NONE",
        user_interaction: "NONE",
        scope: "UNCHANGED",
        confidentiality_impact: "NONE",
        integrity_impact: "LOW",
        availability_impact: "NONE",
        base_score: 4.3,
        base_severity: "MEDIUM",
      },
      exploitability_score: 2.8,
      impact_score: 1.4,
    },
  },
  {
    id: 17960,
    cwe_code: "CWE-471",
    description:
      "An attacker could prepare a specially crafted project file that, if opened, would attempt to connect to the cloud and trigger a man in the middle (MiTM) attack. This could allow an attacker to obtain credentials and take over the user\u2019s cloud account.",
    code: "CVE-2021-42701",
    published: "2021-11-05T16:15Z",
    modified: "2021-11-09T14:48Z",
    version: "4.0",
    assigner: "ics-cert@hq.dhs.gov",
    data_format: "MITRE",
    references_list: [
      {
        name: "https://us-cert.cisa.gov/ics/advisories/icsa-21-308-02",
        url: "https://us-cert.cisa.gov/ics/advisories/icsa-21-308-02",
        refsource: "MISC",
        tags: ["third_party_advisory", "us_government_resource"],
      },
    ],
    cpe_list: [
      {
        uri: "cpe:2.3:a:azeotech:daqfactory:*:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:a:azeotech:daqfactory:18.1:build_2347:*:*:*:*:*:*",
        is_vulnerable: true,
      },
    ],
    base_metric_v2: {
      cvss_v2: {
        vector: "AV:N/AC:H/Au:N/C:P/I:N/A:N",
        version: "2.0",
        access_vector: "NETWORK",
        access_complexity: "HIGH",
        authentication: "NONE",
        confidentiality_impact: "PARTIAL",
        integrity_impact: "NONE",
        availability_impact: "NONE",
        base_score: 2.6,
      },
      severity: "LOW",
      exploitability_score: 4.9,
      impact_score: 2.9,
      is_obtain_all_privilege: false,
      is_obtain_user_privilege: false,
      is_obtain_other_privilege: false,
      is_user_interaction_required: true,
    },
    base_metric_v3: {
      cvss_v3: {
        vector: "CVSS:3.1/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:N",
        version: "3.1",
        attack_vector: "LOCAL",
        attack_complexity: "HIGH",
        privileges_required: "NONE",
        user_interaction: "NONE",
        scope: "UNCHANGED",
        confidentiality_impact: "HIGH",
        integrity_impact: "HIGH",
        availability_impact: "NONE",
        base_score: 6.3,
        base_severity: "MEDIUM",
      },
      exploitability_score: 1.0,
      impact_score: 5.2,
    },
  },
  {
    id: 10640,
    cwe_code: "CWE-471",
    description:
      "Highlight.js is a syntax highlighter written in JavaScript. Highlight.js versions before 9.18.2 and 10.1.2 are vulnerable to Prototype Pollution. A malicious HTML code block can be crafted that will result in prototype pollution of the base object's prototype during highlighting. If you allow users to insert custom HTML code blocks into your page/app via parsing Markdown code blocks (or similar) and do not filter the language names the user can provide you may be vulnerable. The pollution should just be harmless data but this can cause problems for applications not expecting these properties to exist and can result in strange behavior or application crashes, i.e. a potential DOS vector. If your website or application does not render user provided data it should be unaffected. Versions 9.18.2 and 10.1.2 and newer include fixes for this vulnerability. If you are using version 7 or 8 you are encouraged to upgrade to a newer release.",
    code: "CVE-2020-26237",
    published: "2020-11-24T23:15Z",
    modified: "2020-12-31T02:15Z",
    version: "4.0",
    assigner: "security-advisories@github.com",
    data_format: "MITRE",
    references_list: [
      {
        name: "https://github.com/highlightjs/highlight.js/security/advisories/GHSA-vfrc-7r7c-w9mx",
        url: "https://github.com/highlightjs/highlight.js/security/advisories/GHSA-vfrc-7r7c-w9mx",
        refsource: "CONFIRM",
        tags: ["mitigation", "third_party_advisory"],
      },
      {
        name: "https://www.npmjs.com/package/highlight.js",
        url: "https://www.npmjs.com/package/highlight.js",
        refsource: "MISC",
        tags: ["third_party_advisory"],
      },
      {
        name: "https://github.com/highlightjs/highlight.js/pull/2636",
        url: "https://github.com/highlightjs/highlight.js/pull/2636",
        refsource: "MISC",
        tags: ["patch", "third_party_advisory"],
      },
      {
        name: "https://github.com/highlightjs/highlight.js/commit/7241013ae011a585983e176ddc0489a7a52f6bb0",
        url: "https://github.com/highlightjs/highlight.js/commit/7241013ae011a585983e176ddc0489a7a52f6bb0",
        refsource: "MISC",
        tags: ["patch", "third_party_advisory"],
      },
      {
        name: "[debian-lts-announce] 20201230 [SECURITY] [DLA 2511-1] highlight.js security update",
        url: "https://lists.debian.org/debian-lts-announce/2020/12/msg00041.html",
        refsource: "MLIST",
        tags: [],
      },
    ],
    cpe_list: [
      {
        uri: "cpe:2.3:a:highlightjs:highlight.js:*:*:*:*:*:node.js:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:a:highlightjs:highlight.js:*:*:*:*:*:node.js:*:*",
        is_vulnerable: true,
      },
    ],
    base_metric_v2: {
      cvss_v2: {
        vector: "AV:N/AC:M/Au:S/C:N/I:P/A:P",
        version: "2.0",
        access_vector: "NETWORK",
        access_complexity: "MEDIUM",
        authentication: "SINGLE",
        confidentiality_impact: "NONE",
        integrity_impact: "PARTIAL",
        availability_impact: "PARTIAL",
        base_score: 4.9,
      },
      severity: "MEDIUM",
      exploitability_score: 6.8,
      impact_score: 4.9,
      is_obtain_all_privilege: false,
      is_obtain_user_privilege: false,
      is_obtain_other_privilege: false,
      is_user_interaction_required: true,
    },
    base_metric_v3: {
      cvss_v3: {
        vector: "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:N/I:H/A:N",
        version: "3.1",
        attack_vector: "NETWORK",
        attack_complexity: "LOW",
        privileges_required: "LOW",
        user_interaction: "LOW",
        scope: "CHANGED",
        confidentiality_impact: "NONE",
        integrity_impact: "HIGH",
        availability_impact: "NONE",
        base_score: 6.8,
        base_severity: "MEDIUM",
      },
      exploitability_score: 2.3,
      impact_score: 4.0,
    },
  },
  {
    id: 12276,
    cwe_code: "CWE-471",
    description:
      "hoek node module before 4.2.0 and 5.0.x before 5.0.3 suffers from a Modification of Assumed-Immutable Data (MAID) vulnerability via 'merge' and 'applyToDefaults' functions, which allows a malicious user to modify the prototype of \"Object\" via __proto__, causing the addition or modification of an existing property that will exist on all objects.",
    code: "CVE-2018-3728",
    published: "2018-03-30T19:29Z",
    modified: "2019-10-09T23:40Z",
    version: "4.0",
    assigner: "cve-assignments@hackerone.com",
    data_format: "MITRE",
    references_list: [
      {
        name: "https://hackerone.com/reports/310439",
        url: "https://hackerone.com/reports/310439",
        refsource: "MISC",
        tags: ["exploit", "third_party_advisory"],
      },
      {
        name: "https://github.com/hapijs/hoek/commit/32ed5c9413321fbc37da5ca81a7cbab693786dee",
        url: "https://github.com/hapijs/hoek/commit/32ed5c9413321fbc37da5ca81a7cbab693786dee",
        refsource: "CONFIRM",
        tags: ["patch", "third_party_advisory"],
      },
      {
        name: "103108",
        url: "http://www.securityfocus.com/bid/103108",
        refsource: "BID",
        tags: ["third_party_advisory", "vdb_entry"],
      },
      {
        name: "https://snyk.io/vuln/npm:hoek:20180212",
        url: "https://snyk.io/vuln/npm:hoek:20180212",
        refsource: "MISC",
        tags: ["exploit", "patch", "third_party_advisory"],
      },
      {
        name: "https://nodesecurity.io/advisories/566",
        url: "https://nodesecurity.io/advisories/566",
        refsource: "CONFIRM",
        tags: ["broken_link"],
      },
      {
        name: "RHSA-2018:1263",
        url: "https://access.redhat.com/errata/RHSA-2018:1263",
        refsource: "REDHAT",
        tags: ["third_party_advisory"],
      },
      {
        name: "RHSA-2018:1264",
        url: "https://access.redhat.com/errata/RHSA-2018:1264",
        refsource: "REDHAT",
        tags: ["third_party_advisory"],
      },
    ],
    cpe_list: [
      {
        uri: "cpe:2.3:a:hapijs:hoek:*:*:*:*:*:node.js:*:*",
        is_vulnerable: true,
      },
      {
        uri: "cpe:2.3:a:hapijs:hoek:*:*:*:*:*:node.js:*:*",
        is_vulnerable: true,
      },
    ],
    base_metric_v2: {
      cvss_v2: {
        vector: "AV:N/AC:L/Au:S/C:P/I:P/A:P",
        version: "2.0",
        access_vector: "NETWORK",
        access_complexity: "LOW",
        authentication: "SINGLE",
        confidentiality_impact: "PARTIAL",
        integrity_impact: "PARTIAL",
        availability_impact: "PARTIAL",
        base_score: 6.5,
      },
      severity: "MEDIUM",
      exploitability_score: 8.0,
      impact_score: 6.4,
      is_obtain_all_privilege: false,
      is_obtain_user_privilege: false,
      is_obtain_other_privilege: false,
      is_user_interaction_required: false,
    },
    base_metric_v3: {
      cvss_v3: {
        vector: "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
        version: "3.0",
        attack_vector: "NETWORK",
        attack_complexity: "LOW",
        privileges_required: "LOW",
        user_interaction: "LOW",
        scope: "UNCHANGED",
        confidentiality_impact: "HIGH",
        integrity_impact: "HIGH",
        availability_impact: "HIGH",
        base_score: 8.8,
        base_severity: "HIGH",
      },
      exploitability_score: 2.8,
      impact_score: 5.9,
    },
  },

  {
    id: 609,
    cwe_code: "CWE-840",
    description:
      "Business Logic Errors in GitHub repository microweber/microweber prior to 1.2.20.",
    code: "CVE-2022-2368",
    published: "2022-07-11T08:15Z",
    modified: "2022-07-15T17:34Z",
    version: "4.0",
    assigner: "security@huntr.dev",
    data_format: "MITRE",
    references_list: [
      {
        name: "https://huntr.dev/bounties/a9595eda-a5e0-4717-8d64-b445ef83f452",
        url: "https://huntr.dev/bounties/a9595eda-a5e0-4717-8d64-b445ef83f452",
        refsource: "CONFIRM",
        tags: ["exploit", "patch", "third_party_advisory"],
      },
      {
        name: "https://github.com/microweber/microweber/commit/53c000ccd5602536e28b15d9630eb8261b04a302",
        url: "https://github.com/microweber/microweber/commit/53c000ccd5602536e28b15d9630eb8261b04a302",
        refsource: "MISC",
        tags: ["patch", "third_party_advisory"],
      },
    ],
    cpe_list: [
      {
        uri: "cpe:2.3:a:microweber:microweber:*:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
    ],
    base_metric_v2: {
      cvss_v2: {
        vector: "AV:N/AC:L/Au:N/C:P/I:P/A:P",
        version: "2.0",
        access_vector: "NETWORK",
        access_complexity: "LOW",
        authentication: "NONE",
        confidentiality_impact: "PARTIAL",
        integrity_impact: "PARTIAL",
        availability_impact: "PARTIAL",
        base_score: 7.5,
      },
      severity: "HIGH",
      exploitability_score: 10.0,
      impact_score: 6.4,
      is_obtain_all_privilege: false,
      is_obtain_user_privilege: false,
      is_obtain_other_privilege: false,
      is_user_interaction_required: false,
    },
    base_metric_v3: {
      cvss_v3: {
        vector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        version: "3.1",
        attack_vector: "NETWORK",
        attack_complexity: "LOW",
        privileges_required: "NONE",
        user_interaction: "NONE",
        scope: "UNCHANGED",
        confidentiality_impact: "HIGH",
        integrity_impact: "HIGH",
        availability_impact: "HIGH",
        base_score: 9.8,
        base_severity: "CRITICAL",
      },
      exploitability_score: 3.9,
      impact_score: 5.9,
    },
  },
  {
    id: 609,
    cwe_code: "CWE-840",
    description:
      "Business Logic Errors in GitHub repository microweber/microweber prior to 1.2.20.",
    code: "CVE-2022-2368",
    published: "2022-07-11T08:15Z",
    modified: "2022-07-15T17:34Z",
    version: "4.0",
    assigner: "security@huntr.dev",
    data_format: "MITRE",
    references_list: [
      {
        name: "https://huntr.dev/bounties/a9595eda-a5e0-4717-8d64-b445ef83f452",
        url: "https://huntr.dev/bounties/a9595eda-a5e0-4717-8d64-b445ef83f452",
        refsource: "CONFIRM",
        tags: ["exploit", "patch", "third_party_advisory"],
      },
      {
        name: "https://github.com/microweber/microweber/commit/53c000ccd5602536e28b15d9630eb8261b04a302",
        url: "https://github.com/microweber/microweber/commit/53c000ccd5602536e28b15d9630eb8261b04a302",
        refsource: "MISC",
        tags: ["patch", "third_party_advisory"],
      },
    ],
    cpe_list: [
      {
        uri: "cpe:2.3:a:microweber:microweber:*:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
    ],
    base_metric_v2: {
      cvss_v2: {
        vector: "AV:N/AC:L/Au:N/C:P/I:P/A:P",
        version: "2.0",
        access_vector: "NETWORK",
        access_complexity: "LOW",
        authentication: "NONE",
        confidentiality_impact: "PARTIAL",
        integrity_impact: "PARTIAL",
        availability_impact: "PARTIAL",
        base_score: 7.5,
      },
      severity: "HIGH",
      exploitability_score: 10.0,
      impact_score: 6.4,
      is_obtain_all_privilege: false,
      is_obtain_user_privilege: false,
      is_obtain_other_privilege: false,
      is_user_interaction_required: false,
    },
    base_metric_v3: {
      cvss_v3: {
        vector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        version: "3.1",
        attack_vector: "NETWORK",
        attack_complexity: "LOW",
        privileges_required: "NONE",
        user_interaction: "NONE",
        scope: "UNCHANGED",
        confidentiality_impact: "HIGH",
        integrity_impact: "HIGH",
        availability_impact: "HIGH",
        base_score: 9.8,
        base_severity: "CRITICAL",
      },
      exploitability_score: 3.9,
      impact_score: 5.9,
    },
  },
  {
    id: 308,
    cwe_code: "CWE-840",
    description:
      "Business Logic Errors in Packagist dolibarr/dolibarr prior to 16.0.",
    code: "CVE-2022-0414",
    published: "2022-01-31T11:15Z",
    modified: "2022-03-17T16:19Z",
    version: "4.0",
    assigner: "security@huntr.dev",
    data_format: "MITRE",
    references_list: [
      {
        name: "https://github.com/dolibarr/dolibarr/commit/37fb02ee760cfff18c795ba468da1ba1c53f4684",
        url: "https://github.com/dolibarr/dolibarr/commit/37fb02ee760cfff18c795ba468da1ba1c53f4684",
        refsource: "MISC",
        tags: ["patch", "third_party_advisory"],
      },
      {
        name: "https://huntr.dev/bounties/76f3b405-9f5d-44b1-8434-b52b56ee395f",
        url: "https://huntr.dev/bounties/76f3b405-9f5d-44b1-8434-b52b56ee395f",
        refsource: "CONFIRM",
        tags: ["exploit", "patch", "third_party_advisory"],
      },
    ],
    cpe_list: [
      {
        uri: "cpe:2.3:a:dolibarr:dolibarr:*:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
    ],
    base_metric_v2: {
      cvss_v2: {
        vector: "AV:N/AC:L/Au:S/C:N/I:P/A:N",
        version: "2.0",
        access_vector: "NETWORK",
        access_complexity: "LOW",
        authentication: "SINGLE",
        confidentiality_impact: "NONE",
        integrity_impact: "PARTIAL",
        availability_impact: "NONE",
        base_score: 4.0,
      },
      severity: "MEDIUM",
      exploitability_score: 8.0,
      impact_score: 2.9,
      is_obtain_all_privilege: false,
      is_obtain_user_privilege: false,
      is_obtain_other_privilege: false,
      is_user_interaction_required: false,
    },
    base_metric_v3: {
      cvss_v3: {
        vector: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N",
        version: "3.1",
        attack_vector: "NETWORK",
        attack_complexity: "LOW",
        privileges_required: "LOW",
        user_interaction: "LOW",
        scope: "UNCHANGED",
        confidentiality_impact: "NONE",
        integrity_impact: "LOW",
        availability_impact: "NONE",
        base_score: 4.3,
        base_severity: "MEDIUM",
      },
      exploitability_score: 2.8,
      impact_score: 1.4,
    },
  },
  {
    id: 405,
    cwe_code: "CWE-840",
    description:
      "Business Logic Errors in GitHub repository publify/publify prior to 9.2.7.",
    code: "CVE-2022-0524",
    published: "2022-02-08T22:15Z",
    modified: "2022-02-11T18:59Z",
    version: "4.0",
    assigner: "security@huntr.dev",
    data_format: "MITRE",
    references_list: [
      {
        name: "https://github.com/publify/publify/commit/16fceecadbe80ab0ef846b62a12dc7bfff10b8c5",
        url: "https://github.com/publify/publify/commit/16fceecadbe80ab0ef846b62a12dc7bfff10b8c5",
        refsource: "MISC",
        tags: ["patch", "third_party_advisory"],
      },
      {
        name: "https://huntr.dev/bounties/bfffae58-b3cd-4e0e-b1f2-3db387a22c3d",
        url: "https://huntr.dev/bounties/bfffae58-b3cd-4e0e-b1f2-3db387a22c3d",
        refsource: "CONFIRM",
        tags: ["exploit", "third_party_advisory"],
      },
    ],
    cpe_list: [
      {
        uri: "cpe:2.3:a:publify_project:publify:*:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
    ],
    base_metric_v2: {
      cvss_v2: {
        vector: "AV:N/AC:L/Au:N/C:P/I:N/A:N",
        version: "2.0",
        access_vector: "NETWORK",
        access_complexity: "LOW",
        authentication: "NONE",
        confidentiality_impact: "PARTIAL",
        integrity_impact: "NONE",
        availability_impact: "NONE",
        base_score: 5.0,
      },
      severity: "MEDIUM",
      exploitability_score: 10.0,
      impact_score: 2.9,
      is_obtain_all_privilege: false,
      is_obtain_user_privilege: false,
      is_obtain_other_privilege: false,
      is_user_interaction_required: false,
    },
    base_metric_v3: {
      cvss_v3: {
        vector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
        version: "3.1",
        attack_vector: "NETWORK",
        attack_complexity: "LOW",
        privileges_required: "NONE",
        user_interaction: "NONE",
        scope: "UNCHANGED",
        confidentiality_impact: "HIGH",
        integrity_impact: "NONE",
        availability_impact: "NONE",
        base_score: 7.5,
        base_severity: "HIGH",
      },
      exploitability_score: 3.9,
      impact_score: 3.6,
    },
  },
  {
    id: 469,
    cwe_code: "CWE-840",
    description:
      "Business Logic Errors in Packagist microweber/microweber prior to 1.2.11.",
    code: "CVE-2022-0596",
    published: "2022-02-15T14:15Z",
    modified: "2022-02-23T15:59Z",
    version: "4.0",
    assigner: "security@huntr.dev",
    data_format: "MITRE",
    references_list: [
      {
        name: "https://huntr.dev/bounties/f68b994e-2b8b-49f5-af2a-8cd99e8048a5",
        url: "https://huntr.dev/bounties/f68b994e-2b8b-49f5-af2a-8cd99e8048a5",
        refsource: "CONFIRM",
        tags: ["exploit", "issue_tracking", "patch", "third_party_advisory"],
      },
      {
        name: "https://github.com/microweber/microweber/commit/91a9d899741557c75050614ff7adb8c0e3feb005",
        url: "https://github.com/microweber/microweber/commit/91a9d899741557c75050614ff7adb8c0e3feb005",
        refsource: "MISC",
        tags: ["patch", "third_party_advisory"],
      },
    ],
    cpe_list: [
      {
        uri: "cpe:2.3:a:microweber:microweber:*:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
    ],
    base_metric_v2: {
      cvss_v2: {
        vector: "AV:N/AC:L/Au:S/C:N/I:P/A:N",
        version: "2.0",
        access_vector: "NETWORK",
        access_complexity: "LOW",
        authentication: "SINGLE",
        confidentiality_impact: "NONE",
        integrity_impact: "PARTIAL",
        availability_impact: "NONE",
        base_score: 4.0,
      },
      severity: "MEDIUM",
      exploitability_score: 8.0,
      impact_score: 2.9,
      is_obtain_all_privilege: false,
      is_obtain_user_privilege: false,
      is_obtain_other_privilege: false,
      is_user_interaction_required: false,
    },
    base_metric_v3: {
      cvss_v3: {
        vector: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N",
        version: "3.1",
        attack_vector: "NETWORK",
        attack_complexity: "LOW",
        privileges_required: "LOW",
        user_interaction: "LOW",
        scope: "UNCHANGED",
        confidentiality_impact: "NONE",
        integrity_impact: "LOW",
        availability_impact: "NONE",
        base_score: 4.3,
        base_severity: "MEDIUM",
      },
      exploitability_score: 2.8,
      impact_score: 1.4,
    },
  },
  {
    id: 3726,
    cwe_code: "CWE-840",
    description:
      "Business Logic Errors in GitHub repository microweber/microweber prior to 1.2.20.",
    code: "CVE-2022-2368",
    published: "2022-07-11T08:15Z",
    modified: "2022-07-15T17:34Z",
    version: "4.0",
    assigner: "security@huntr.dev",
    data_format: "MITRE",
    references_list: [
      {
        name: "https://huntr.dev/bounties/a9595eda-a5e0-4717-8d64-b445ef83f452",
        url: "https://huntr.dev/bounties/a9595eda-a5e0-4717-8d64-b445ef83f452",
        refsource: "CONFIRM",
        tags: ["exploit", "patch", "third_party_advisory"],
      },
      {
        name: "https://github.com/microweber/microweber/commit/53c000ccd5602536e28b15d9630eb8261b04a302",
        url: "https://github.com/microweber/microweber/commit/53c000ccd5602536e28b15d9630eb8261b04a302",
        refsource: "MISC",
        tags: ["patch", "third_party_advisory"],
      },
    ],
    cpe_list: [
      {
        uri: "cpe:2.3:a:microweber:microweber:*:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
    ],
    base_metric_v2: {
      cvss_v2: {
        vector: "AV:N/AC:L/Au:N/C:P/I:P/A:P",
        version: "2.0",
        access_vector: "NETWORK",
        access_complexity: "LOW",
        authentication: "NONE",
        confidentiality_impact: "PARTIAL",
        integrity_impact: "PARTIAL",
        availability_impact: "PARTIAL",
        base_score: 7.5,
      },
      severity: "HIGH",
      exploitability_score: 10.0,
      impact_score: 6.4,
      is_obtain_all_privilege: false,
      is_obtain_user_privilege: false,
      is_obtain_other_privilege: false,
      is_user_interaction_required: false,
    },
    base_metric_v3: {
      cvss_v3: {
        vector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        version: "3.1",
        attack_vector: "NETWORK",
        attack_complexity: "LOW",
        privileges_required: "NONE",
        user_interaction: "NONE",
        scope: "UNCHANGED",
        confidentiality_impact: "HIGH",
        integrity_impact: "HIGH",
        availability_impact: "HIGH",
        base_score: 9.8,
        base_severity: "CRITICAL",
      },
      exploitability_score: 3.9,
      impact_score: 5.9,
    },
  },
  {
    id: 16957,
    cwe_code: "CWE-840",
    description: "yetiforcecrm is vulnerable to Business Logic Errors",
    code: "CVE-2021-4111",
    published: "2021-12-15T09:15Z",
    modified: "2021-12-17T14:50Z",
    version: "4.0",
    assigner: "security@huntr.dev",
    data_format: "MITRE",
    references_list: [
      {
        name: "https://huntr.dev/bounties/8afc8981-baff-4082-b640-be535b29eb9a",
        url: "https://huntr.dev/bounties/8afc8981-baff-4082-b640-be535b29eb9a",
        refsource: "CONFIRM",
        tags: ["exploit", "issue_tracking", "patch", "third_party_advisory"],
      },
      {
        name: "https://github.com/yetiforcecompany/yetiforcecrm/commit/c1ad7111a090adfcd5898af40724907adc987acf",
        url: "https://github.com/yetiforcecompany/yetiforcecrm/commit/c1ad7111a090adfcd5898af40724907adc987acf",
        refsource: "MISC",
        tags: ["patch", "third_party_advisory"],
      },
    ],
    cpe_list: [
      {
        uri: "cpe:2.3:a:yetiforce:yetiforce_customer_relationship_management:*:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
    ],
    base_metric_v2: {
      cvss_v2: {
        vector: "AV:N/AC:L/Au:S/C:N/I:P/A:N",
        version: "2.0",
        access_vector: "NETWORK",
        access_complexity: "LOW",
        authentication: "SINGLE",
        confidentiality_impact: "NONE",
        integrity_impact: "PARTIAL",
        availability_impact: "NONE",
        base_score: 4.0,
      },
      severity: "MEDIUM",
      exploitability_score: 8.0,
      impact_score: 2.9,
      is_obtain_all_privilege: false,
      is_obtain_user_privilege: false,
      is_obtain_other_privilege: false,
      is_user_interaction_required: false,
    },
    base_metric_v3: {
      cvss_v3: {
        vector: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N",
        version: "3.1",
        attack_vector: "NETWORK",
        attack_complexity: "LOW",
        privileges_required: "LOW",
        user_interaction: "LOW",
        scope: "UNCHANGED",
        confidentiality_impact: "NONE",
        integrity_impact: "LOW",
        availability_impact: "NONE",
        base_score: 4.3,
        base_severity: "MEDIUM",
      },
      exploitability_score: 2.8,
      impact_score: 1.4,
    },
  },
  {
    id: 17020,
    cwe_code: "CWE-840",
    description: "yetiforcecrm is vulnerable to Business Logic Errors",
    code: "CVE-2021-4117",
    published: "2021-12-15T15:15Z",
    modified: "2021-12-17T14:19Z",
    version: "4.0",
    assigner: "security@huntr.dev",
    data_format: "MITRE",
    references_list: [
      {
        name: "https://huntr.dev/bounties/0b81e572-bdc9-4caf-aa02-81f3c7ad7c0a",
        url: "https://huntr.dev/bounties/0b81e572-bdc9-4caf-aa02-81f3c7ad7c0a",
        refsource: "CONFIRM",
        tags: ["exploit", "issue_tracking", "patch", "third_party_advisory"],
      },
      {
        name: "https://github.com/yetiforcecompany/yetiforcecrm/commit/8dccd93442725f245b4b71986bbe6f4f48639239",
        url: "https://github.com/yetiforcecompany/yetiforcecrm/commit/8dccd93442725f245b4b71986bbe6f4f48639239",
        refsource: "MISC",
        tags: ["patch", "third_party_advisory"],
      },
    ],
    cpe_list: [
      {
        uri: "cpe:2.3:a:yetiforce:yetiforce_customer_relationship_management:*:*:*:*:*:*:*:*",
        is_vulnerable: true,
      },
    ],
    base_metric_v2: {
      cvss_v2: {
        vector: "AV:N/AC:L/Au:S/C:N/I:P/A:N",
        version: "2.0",
        access_vector: "NETWORK",
        access_complexity: "LOW",
        authentication: "SINGLE",
        confidentiality_impact: "NONE",
        integrity_impact: "PARTIAL",
        availability_impact: "NONE",
        base_score: 4.0,
      },
      severity: "MEDIUM",
      exploitability_score: 8.0,
      impact_score: 2.9,
      is_obtain_all_privilege: false,
      is_obtain_user_privilege: false,
      is_obtain_other_privilege: false,
      is_user_interaction_required: false,
    },
    base_metric_v3: {
      cvss_v3: {
        vector: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N",
        version: "3.1",
        attack_vector: "NETWORK",
        attack_complexity: "LOW",
        privileges_required: "LOW",
        user_interaction: "LOW",
        scope: "UNCHANGED",
        confidentiality_impact: "NONE",
        integrity_impact: "LOW",
        availability_impact: "NONE",
        base_score: 4.3,
        base_severity: "MEDIUM",
      },
      exploitability_score: 2.8,
      impact_score: 1.4,
    },
  },
];
