export const dummyCve = {
  id: 10283,
  cwe_code: "CWE-567",
  description:
    "A flaw was found in RESTEasy, where an incorrect response to an HTTP request is provided. This flaw allows an attacker to gain access to privileged information. The highest threat from this vulnerability is to confidentiality and integrity. Versions before resteasy 2.0.0.Alpha3 are affected.",
  code: "CVE-2020-25724",
  published: "2021-05-26T21:15Z",
  modified: "2022-05-13T20:46Z",
  version: "4.0",
  assigner: "secalert@redhat.com",
  data_format: "MITRE",
  references_list: [
    {
      name: "https://bugzilla.redhat.com/show_bug.cgi?id=1899354",
      url: "https://bugzilla.redhat.com/show_bug.cgi?id=1899354",
      refsource: "MISC",
      tags: ["issue_tracking", "vendor_advisory"],
    },
    {
      name: "https://security.netapp.com/advisory/ntap-20210702-0003/",
      url: "https://security.netapp.com/advisory/ntap-20210702-0003/",
      refsource: "CONFIRM",
      tags: ["third_party_advisory"],
    },
  ],
  cpe_list: [
    {
      uri: "cpe:2.3:a:redhat:resteasy:2.0.0:alpha1:*:*:*:*:*:*",
      is_vulnerable: true,
    },
    {
      uri: "cpe:2.3:a:redhat:resteasy:*:*:*:*:*:*:*:*",
      is_vulnerable: true,
    },
    {
      uri: "cpe:2.3:a:redhat:resteasy:2.0.0:alpha2:*:*:*:*:*:*",
      is_vulnerable: true,
    },
    {
      uri: "cpe:2.3:a:quarkus:quarkus:*:*:*:*:*:*:*:*",
      is_vulnerable: true,
    },
  ],
  base_metric_v2: {
    cvss_v2: {
      vector: "AV:N/AC:L/Au:S/C:P/I:N/A:N",
      version: "2.0",
      access_vector: "NETWORK",
      access_complexity: "LOW",
      authentication: "SINGLE",
      confidentiality_impact: "PARTIAL",
      integrity_impact: "NONE",
      availability_impact: "NONE",
      base_score: 4.0,
    },
    severity: "MEDIUM",
    exploitability_score: 8.0,
    impact_score: 2.9,
    is_obtain_all_privilege: false,
    is_obtain_user_privilege: false,
    is_obtain_other_privilege: false,
    is_user_interaction_required: false,
  },
  base_metric_v3: {
    cvss_v3: {
      vector: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N",
      version: "3.1",
      attack_vector: "NETWORK",
      attack_complexity: "LOW",
      privileges_required: "LOW",
      user_interaction: "LOW",
      scope: "UNCHANGED",
      confidentiality_impact: "LOW",
      integrity_impact: "NONE",
      availability_impact: "NONE",
      base_score: 4.3,
      base_severity: "MEDIUM",
    },
    exploitability_score: 2.8,
    impact_score: 1.4,
  },
};
