class FeedsUrls:
    def __init__(self):
        self._capec = "http://capec.mitre.org/data/definitions/76.html"
        self._first = "https://www.first.org/"
        self._findwide = "http://findwide.com/"
        self._github_advisories = "https://github.com/advisories"
        self._vuldb = "https://vuldb.com/?doc.api"
        self._capec = "http://capec.mitre.org/data/"
        self._dnstwist = "https://dnstwist.it/"
        self._sec_gov = "https://www.sec.gov/edgar.shtml"
        self._hackerpom = "https://www.hackerpom.com/feed"
        self._hyp3rlinx = "http://hyp3rlinx.altervista.org/"
        self._github_advisories = "https://github.com/advisories"
        self._chtsecurity = "https://www.chtsecurity.com/"
        self._ubuntu = "https://ubuntu.com/security/notices"
        self._attack_matrix = "https://attack.mitre.org/"
