# Generated by Django 3.1.7 on 2021-03-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CensysCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(default='', max_length=72, unique=True)),
                ('secret', models.CharField(default='', max_length=64, unique=True)),
                ('base_url', models.CharField(default='https://censys.io/', max_length=36, unique=True)),
                ('api_url', models.CharField(default='https://censys.io/api/v1', max_length=48, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShodanCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=200, unique=True)),
                ('api_key', models.CharField(default='', max_length=64, unique=True)),
                ('base_url', models.CharField(default='https://www.shodan.io/', max_length=44, unique=True)),
                ('api_url', models.CharField(default='https://developer.shodan.io/api', max_length=62, unique=True)),
            ],
        ),
    ]
