# Generated by Django 3.1.7 on 2021-06-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='cwe',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vector',
            name='version',
            field=models.CharField(choices=[('3', 'CVSSV3'), ('2', 'CVSSV2')], max_length=6),
        ),
    ]
