# Generated by Django 4.0 on 2022-02-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwe',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cwe',
            name='name',
            field=models.TextField(),
        ),
    ]
