# Generated by Django 4.0.5 on 2022-06-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemetricv2',
            name='is_user_interaction_required',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cvssv3',
            name='availability_impact',
            field=models.CharField(choices=[('COMPLETE', 'complete'), ('PARTIAL', 'partial'), ('NONE', 'none'), ('HIGH', 'high')], max_length=20),
        ),
    ]
