# Generated by Django 4.0.5 on 2022-06-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CPE',
        ),
        migrations.RemoveField(
            model_name='referencetag',
            name='reference',
        ),
        migrations.DeleteModel(
            name='CVE',
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
        migrations.DeleteModel(
            name='ReferenceTag',
        ),
        migrations.DeleteModel(
            name='Vector',
        ),
    ]
