# Generated by Django 4.0.5 on 2022-07-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0002_assigner_cve_format_reference_vector_version_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemetricv2',
            name='cve',
            field=models.ManyToManyField(blank=True, null=True, to='vulnerabilities.cve'),
        ),
    ]
