# Generated by Django 3.1.7 on 2021-06-28 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0002_auto_20210628_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='cve',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vector_list', to='vulnerabilities.cve'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpe',
            name='cve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpe_list', to='vulnerabilities.cve'),
        ),
        migrations.AlterField(
            model_name='cve',
            name='cwe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cve_list', to='vulnerabilities.cwe'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='cve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_list', to='vulnerabilities.cve'),
        ),
    ]
