# Generated by Django 3.1.7 on 2021-06-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0003_auto_20210628_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwe',
            name='short_description',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
