# Generated by Django 4.0.5 on 2022-07-10 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0003_alter_basemetricv2_cve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemetricv2',
            name='cvss_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vulnerabilities.cvssv2'),
        ),
    ]
