# Generated by Django 3.1.7 on 2021-06-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0004_cwe_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vector',
            name='version',
            field=models.CharField(choices=[('3.1', 'CVSSV3.1'), ('3.0', 'CVSSV3.0'), ('2.0', 'CVSSV2.0')], max_length=6),
        ),
    ]
