# Generated by Django 3.1.7 on 2021-07-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0007_auto_20210630_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cwe',
            name='code',
        ),
        migrations.AlterField(
            model_name='cve',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cwe',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
