# Generated by Django 3.1.7 on 2021-07-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0008_auto_20210719_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cve',
            name='code',
        ),
    ]
