# Generated by Django 3.1.7 on 2021-07-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0010_auto_20210719_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpe',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
