# Generated by Django 3.1.7 on 2021-07-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0012_auto_20210719_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cwe',
            name='short_description',
        ),
        migrations.AddField(
            model_name='cwe',
            name='abstraction',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cwe',
            name='extended_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cwe',
            name='name',
            field=models.CharField(default=' ', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cwe',
            name='status',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cwe',
            name='structure',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cwe',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
